package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades implements java.io.Serializable {

    private Integer id;
    private Departamentos departamentos;
    private String nombre;
    private Set proveedoreses = new HashSet(0);

    public Ciudades() {
    }

    public Ciudades(int id) {
        this.id = id;
    }

    public Ciudades(Departamentos departamentos, String nombre) {
        this.departamentos = departamentos;
        this.nombre = nombre;
    }

    public Ciudades(Departamentos departamentos, String nombre, Set proveedoreses) {
        this.departamentos = departamentos;
        this.nombre = nombre;
        this.proveedoreses = proveedoreses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Departamentos getDepartamentos() {
        return this.departamentos;
    }

    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getProveedoreses() {
        return this.proveedoreses;
    }

    public void setProveedoreses(Set proveedoreses) {
        this.proveedoreses = proveedoreses;
    }

}
