package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer id;
     private Paises paises;
     private String nombre;
     private Set ciudadeses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(Paises paises, String nombre) {
        this.paises = paises;
        this.nombre = nombre;
    }
    public Departamentos(Paises paises, String nombre, Set ciudadeses) {
       this.paises = paises;
       this.nombre = nombre;
       this.ciudadeses = ciudadeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paises getPaises() {
        return this.paises;
    }
    
    public void setPaises(Paises paises) {
        this.paises = paises;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCiudadeses() {
        return this.ciudadeses;
    }
    
    public void setCiudadeses(Set ciudadeses) {
        this.ciudadeses = ciudadeses;
    }




}


