package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Documentos generated by hbm2java
 */
public class Documentos  implements java.io.Serializable {


     private Integer id;
     private Maquinas maquinas;
     private byte[] documento;
     private String estado;
     private Date fchUltAction;
     private String userAction;

    public Documentos() {
    }

    public Documentos(Maquinas maquinas, byte[] documento, String estado, Date fchUltAction, String userAction) {
       this.maquinas = maquinas;
       this.documento = documento;
       this.estado = estado;
       this.fchUltAction = fchUltAction;
       this.userAction = userAction;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Maquinas getMaquinas() {
        return this.maquinas;
    }
    
    public void setMaquinas(Maquinas maquinas) {
        this.maquinas = maquinas;
    }
    public byte[] getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(byte[] documento) {
        this.documento = documento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFchUltAction() {
        return this.fchUltAction;
    }
    
    public void setFchUltAction(Date fchUltAction) {
        this.fchUltAction = fchUltAction;
    }
    public String getUserAction() {
        return this.userAction;
    }
    
    public void setUserAction(String userAction) {
        this.userAction = userAction;
    }




}


