package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Imagenes generated by hbm2java
 */
public class Imagenes  implements java.io.Serializable {


     private Integer id;
     private Maquinas maquinas;
     private String imagen;
     private String estado;
     private Date fchUltAction;
     private String userAction;

    public Imagenes() {
    }
    
    public Imagenes(String estado, int id, String userAction) {
        this.id = id;
        this.estado = estado;
        this.userAction = userAction;
        
    }

    public Imagenes(String imagen, String estado, String userAction, Maquinas maquinas) {
        this.imagen = imagen;
        this.estado = estado;
        this.userAction = userAction;
        this.maquinas = maquinas;
        
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Maquinas getMaquinas() {
        return this.maquinas;
    }
    
    public void setMaquinas(Maquinas maquinas) {
        this.maquinas = maquinas;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFchUltAction() {
        return this.fchUltAction;
    }
    
    public void setFchUltAction(Date fchUltAction) {
        this.fchUltAction = fchUltAction;
    }
    public String getUserAction() {
        return this.userAction;
    }
    
    public void setUserAction(String userAction) {
        this.userAction = userAction;
    }




}


