package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Localizaciones generated by hbm2java
 */
public class Localizaciones  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String codigo;
     private String estado;
     private Date fchUltAction;
     private String userAction;
     private Set seccioneses = new HashSet(0);

    public Localizaciones() {
    }

	
    public Localizaciones(Integer Id) {
        this.id = Id;
    }
    public Localizaciones(String nombre, String codigo, String estado, Date fchUltAction, String userAction) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.estado = estado;
        this.fchUltAction = fchUltAction;
        this.userAction = userAction;
    }
    public Localizaciones(String nombre, String codigo, String estado, Date fchUltAction, String userAction, Set seccioneses) {
       this.nombre = nombre;
       this.codigo = codigo;
       this.estado = estado;
       this.fchUltAction = fchUltAction;
       this.userAction = userAction;
       this.seccioneses = seccioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFchUltAction() {
        return this.fchUltAction;
    }
    
    public void setFchUltAction(Date fchUltAction) {
        this.fchUltAction = fchUltAction;
    }
    public String getUserAction() {
        return this.userAction;
    }
    
    public void setUserAction(String userAction) {
        this.userAction = userAction;
    }
    public Set getSeccioneses() {
        return this.seccioneses;
    }
    
    public void setSeccioneses(Set seccioneses) {
        this.seccioneses = seccioneses;
    }




}


