package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Maquinas generated by hbm2java
 */
public class Maquinas  implements java.io.Serializable {


     private Integer id;
     private Maquinas maquinas;
     private Proveedores proveedores;
     private Secciones secciones;
     private TiposMaquinas tiposMaquinas;
     private Vendedores vendedores;
     private Date fchCompra;
     private Date fchPuestaMarcha;
     private String fabricante;
     private String modelo;
     private String codigo;
     private String potencia;
     private String serial;
     private String marca;
     private String descripcion;
     private String consumoEnergia;
     private Float peso;
     private String observacion;
     private String userAction;
     private String estado;
     private Date fchUltAction;
     private int tiempoGarantia;
     private int tiempoVida;
     private Date vencimientoGarantia;
     private Date vencimientoVida;
     private Set maquinases = new HashSet(0);
     private Set documentoses = new HashSet(0);
     private Set imageneses = new HashSet(0);

    public Maquinas() {
    }

	
    public Maquinas(Integer id) {
        this.id = id;
    }
    /**
     * Constructor new.
     */
    public Maquinas(Date fchCompra, Date fchPuestaMarcha, String fabricante,
            String modelo, String codigo, String potencia, String serial,
            String marca, String consumoEnergia, Float peso, 
            int tiempoGarantia, int tiempoVida, Date vencimientoGarantia,
            Date vencimientoVida, Vendedores vendedores, 
            Proveedores proveedores, TiposMaquinas tiposMaquinas,
            Secciones secciones, Maquinas maquinas,
            String descripcion, String observacion,
            String userAction, String estado) {
        this.vendedores =       vendedores;
        this.maquinas =         maquinas;
        this.proveedores =       proveedores;
        this.secciones =        secciones;
        this.tiposMaquinas =    tiposMaquinas;
        this.fchCompra =        fchCompra;
        this.fchPuestaMarcha =  fchPuestaMarcha;
        this.fabricante =       fabricante;
        this.potencia =         potencia;
        this.modelo =           modelo;
        this.codigo =           codigo;
        this.serial =           serial;
        this.marca =            marca;
        this.consumoEnergia=    consumoEnergia;
        this.peso=              peso;
        this.descripcion =      descripcion;
        this.observacion =      observacion;
        this.userAction =       userAction;
        this.estado =           estado;
        this.tiempoGarantia =   tiempoGarantia;
        this.tiempoVida =       tiempoVida;
        this.vencimientoGarantia = vencimientoGarantia;
        this.vencimientoVida =  vencimientoVida;
    }
    public Maquinas(Maquinas maquinas, Proveedores proveedores, Secciones secciones, TiposMaquinas tiposMaquinas, Vendedores vendedores, Date fchCompra, Date fchPuestaMarcha, String fabricante, String modelo, String codigo, String potencia, String serial, String marca, String descripcion, String consumoEnergia, Float peso, String observacion, String userAction, String estado, Date fchUltAction, int tiempoGarantia, int tiempoVida, Date vencimientoGarantia, Date vencimientoVida, Set maquinases, Set documentoses, Set imageneses) {
       this.maquinas = maquinas;
       this.proveedores = proveedores;
       this.secciones = secciones;
       this.tiposMaquinas = tiposMaquinas;
       this.vendedores = vendedores;
       this.fchCompra = fchCompra;
       this.fchPuestaMarcha = fchPuestaMarcha;
       this.fabricante = fabricante;
       this.modelo = modelo;
       this.codigo = codigo;
       this.potencia = potencia;
       this.serial = serial;
       this.marca = marca;
       this.descripcion = descripcion;
       this.consumoEnergia = consumoEnergia;
       this.peso = peso;
       this.observacion = observacion;
       this.userAction = userAction;
       this.estado = estado;
       this.fchUltAction = fchUltAction;
       this.tiempoGarantia = tiempoGarantia;
       this.tiempoVida = tiempoVida;
       this.vencimientoGarantia = vencimientoGarantia;
       this.vencimientoVida = vencimientoVida;
       this.maquinases = maquinases;
       this.documentoses = documentoses;
       this.imageneses = imageneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Maquinas getMaquinas() {
        return this.maquinas;
    }
    
    public void setMaquinas(Maquinas maquinas) {
        this.maquinas = maquinas;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }
    public TiposMaquinas getTiposMaquinas() {
        return this.tiposMaquinas;
    }
    
    public void setTiposMaquinas(TiposMaquinas tiposMaquinas) {
        this.tiposMaquinas = tiposMaquinas;
    }
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }
    public Date getFchCompra() {
        return this.fchCompra;
    }
    
    public void setFchCompra(Date fchCompra) {
        this.fchCompra = fchCompra;
    }
    public Date getFchPuestaMarcha() {
        return this.fchPuestaMarcha;
    }
    
    public void setFchPuestaMarcha(Date fchPuestaMarcha) {
        this.fchPuestaMarcha = fchPuestaMarcha;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getPotencia() {
        return this.potencia;
    }
    
    public void setPotencia(String potencia) {
        this.potencia = potencia;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getConsumoEnergia() {
        return this.consumoEnergia;
    }
    
    public void setConsumoEnergia(String consumoEnergia) {
        this.consumoEnergia = consumoEnergia;
    }
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getUserAction() {
        return this.userAction;
    }
    
    public void setUserAction(String userAction) {
        this.userAction = userAction;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFchUltAction() {
        return this.fchUltAction;
    }
    
    public void setFchUltAction(Date fchUltAction) {
        this.fchUltAction = fchUltAction;
    }
    public int getTiempoGarantia() {
        return this.tiempoGarantia;
    }
    
    public void setTiempoGarantia(int tiempoGarantia) {
        this.tiempoGarantia = tiempoGarantia;
    }
    public int getTiempoVida() {
        return this.tiempoVida;
    }
    
    public void setTiempoVida(int tiempoVida) {
        this.tiempoVida = tiempoVida;
    }
    public Date getVencimientoGarantia() {
        return this.vencimientoGarantia;
    }
    
    public void setVencimientoGarantia(Date vencimientoGarantia) {
        this.vencimientoGarantia = vencimientoGarantia;
    }
    public Date getVencimientoVida() {
        return this.vencimientoVida;
    }
    
    public void setVencimientoVida(Date vencimientoVida) {
        this.vencimientoVida = vencimientoVida;
    }
    public Set getMaquinases() {
        return this.maquinases;
    }
    
    public void setMaquinases(Set maquinases) {
        this.maquinases = maquinases;
    }
    public Set getDocumentoses() {
        return this.documentoses;
    }
    
    public void setDocumentoses(Set documentoses) {
        this.documentoses = documentoses;
    }
    public Set getImageneses() {
        return this.imageneses;
    }
    
    public void setImageneses(Set imageneses) {
        this.imageneses = imageneses;
    }




}


