package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set departamentoses = new HashSet(0);

    public Paises() {
    }

	
    public Paises(String nombre) {
        this.nombre = nombre;
    }
    public Paises(String nombre, Set departamentoses) {
       this.nombre = nombre;
       this.departamentoses = departamentoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDepartamentoses() {
        return this.departamentoses;
    }
    
    public void setDepartamentoses(Set departamentoses) {
        this.departamentoses = departamentoses;
    }




}


