package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {
    private String pais;
    private String codigo;
    private Set ciudadeses = new HashSet(0);

    public Paises() {
    }

    public String getPais() {
        return pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Set getCiudadeses() {
        return ciudadeses;
    }

    public void setCiudadeses(Set ciudadeses) {
        this.ciudadeses = ciudadeses;
    }
    
    

}


