package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Secciones generated by hbm2java
 */
public class Secciones  implements java.io.Serializable {


     private Integer id;
     private Localizaciones localizaciones;
     private String nombre;
     private String estado;
     private Date fchUltAction;
     private String userAction;
     private String codigo;
     private Set maquinases = new HashSet(0);

    public Secciones() {
    }

    public Secciones(Integer id) {
        this.id = id;
    }
    public Secciones(Localizaciones localizaciones, String nombre, String estado, String userAction, String codigo) {
        this.localizaciones = localizaciones;
        this.nombre = nombre;
        this.estado = estado;
        this.userAction = userAction;
        this.codigo = codigo;
    }
	
    public Secciones(Localizaciones localizaciones, Integer id, String nombre, String estado, String userAction, String codigo) {
        this.id = id;
        this.localizaciones = localizaciones;
        this.nombre = nombre;
        this.estado = estado;
        this.userAction = userAction;
        this.codigo = codigo;
    }
    public Secciones(Localizaciones localizaciones, String nombre, String estado, Date fchUltAction, String userAction, String codigo, Set maquinases) {
       this.localizaciones = localizaciones;
       this.nombre = nombre;
       this.estado = estado;
       this.fchUltAction = fchUltAction;
       this.userAction = userAction;
       this.codigo = codigo;
       this.maquinases = maquinases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Localizaciones getLocalizaciones() {
        return this.localizaciones;
    }
    
    public void setLocalizaciones(Localizaciones localizaciones) {
        this.localizaciones = localizaciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFchUltAction() {
        return this.fchUltAction;
    }
    
    public void setFchUltAction(Date fchUltAction) {
        this.fchUltAction = fchUltAction;
    }
    public String getUserAction() {
        return this.userAction;
    }
    
    public void setUserAction(String userAction) {
        this.userAction = userAction;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getMaquinases() {
        return this.maquinases;
    }
    
    public void setMaquinases(Set maquinases) {
        this.maquinases = maquinases;
    }




}


