package com.esteban.cmms.maven.controller.beans;
// Generated 8/06/2016 05:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedores generated by hbm2java
 */
public class Vendedores  implements java.io.Serializable {


     private Integer id;
     private Proveedores proveedores;
     private String nombre;
     private String email;
     private Integer codigo;
     private String estado;
     private Date fchUltAction;
     private String userAction;
     private Set maquinases = new HashSet(0);

    public Vendedores() {
    }

	
    public Vendedores(Integer id) {
        this.id = id; 
    }

	
    public Vendedores(String nombre, String email, String estado, 
            Date fchUltAction, String userAction) {
        this.nombre = nombre;
        this.email = email;
        this.estado = estado;
        this.fchUltAction = fchUltAction;
        this.userAction = userAction;
    }
    public Vendedores(Integer id, Proveedores proveedores, 
            String nombre, String estado,
            String email, Integer codigo, String userAction) {
       this.id = id;
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.estado = estado;
       this.email = email;
       this.codigo = codigo;
       this.userAction = userAction;
    }
    public Vendedores(Proveedores proveedores, String nombre, 
            String email,String estado, Integer codigo, 
            String userAction) {
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.email = email;
       this.estado = estado;
       this.codigo = codigo;
       this.userAction = userAction;
    }
    public Vendedores(Proveedores proveedores, String nombre, 
            String email, Integer codigo, String estado,
            String userAction, Set maquinases) {
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.email = email;
       this.codigo = codigo;
       this.estado = estado;
       this.userAction = userAction;
       this.maquinases = maquinases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFchUltAction() {
        return this.fchUltAction;
    }
    
    public void setFchUltAction(Date fchUltAction) {
        this.fchUltAction = fchUltAction;
    }
    public String getUserAction() {
        return this.userAction;
    }
    
    public void setUserAction(String userAction) {
        this.userAction = userAction;
    }
    public Set getMaquinases() {
        return this.maquinases;
    }
    
    public void setMaquinases(Set maquinases) {
        this.maquinases = maquinases;
    }




}


